# Generated by Django 2.0.2 on 2018-05-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20180505_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Link'),
        ),
    ]
